Removing encoding keyword in json.load
See https://bugs.python.org/issue39377, but it appears to have been deprecated.

Causing "TypeError: __init__() got an unexpected keyword argument 'encoding'" in python3.9